//
//  SearchInteractor.swift
//  Gitz
//
//  Created by Anderson Oliveira on 28/10/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol SearchInteractorInput {
    
}

protocol SearchInteractorOutput {
    
}

protocol SearchDataSource {
    
}

protocol SearchDataDestination {
    
}

class SearchInteractor: SearchInteractorInput, SearchDataSource, SearchDataDestination {
    
    var output: SearchInteractorOutput?
    
    // MARK: Business logic
    

}
