//
//  SearchPresenter.swift
//  Gitz
//
//  Created by Anderson Oliveira on 28/10/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol SearchPresenterInput {
    
}

protocol SearchPresenterOutput: class {
    
}

class SearchPresenter: SearchPresenterInput {
    
    weak var output: SearchPresenterOutput?
    
    // MARK: Presentation logic
    
}
