//
//  RepositoryRouter.swift
//  Gitz
//
//  Created by Anderson Oliveira on 28/10/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol RepositoryRouterInput {
    
}

protocol RepositoryRouterDataSource: class {
    var selectedRepository: Repository! { get }
}

protocol RepositoryRouterDataDestination: class {
    
}

class RepositoryRouter: RepositoryRouterInput {

    struct SegueIdentifiers {
        static let repositoryDetail = "RepositoryDetailScene"
    }

    weak var viewController: RepositoryViewController!
    weak private var dataSource: RepositoryRouterDataSource!
    weak var dataDestination: RepositoryRouterDataDestination!
    
    init(viewController: RepositoryViewController, dataSource: RepositoryRouterDataSource, dataDestination: RepositoryRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation

    func navigateToRepositoryDetailScene() {
        viewController.performSegue(withIdentifier: SegueIdentifiers.repositoryDetail, sender: self)
    }

    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        switch segue.identifier {
        case SegueIdentifiers.repositoryDetail:
            passDataToRepositoryDetailScene(segue)
        default:
            break
        }
    }

    func passDataToRepositoryDetailScene(_ segue: UIStoryboardSegue) {
        if let repositoryDetailViewController  = segue.destination as? RepositoryDetailViewController {
            repositoryDetailViewController.router?.dataDestination.repository = dataSource.selectedRepository
        }
    }
}
