//
//  RepositoryRouter.swift
//  Gitz
//
//  Created by Anderson Oliveira on 28/10/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol RepositoryRouterInput {
    
}

protocol RepositoryRouterDataSource: class {
    
}

protocol RepositoryRouterDataDestination: class {
    
}

class RepositoryRouter: RepositoryRouterInput {
    
    weak var viewController: RepositoryViewController!
    weak private var dataSource: RepositoryRouterDataSource!
    weak var dataDestination: RepositoryRouterDataDestination!
    
    init(viewController: RepositoryViewController, dataSource: RepositoryRouterDataSource, dataDestination: RepositoryRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
