//
//  RepositoryConfigurator.swift
//  Gitz
//
//  Created by Anderson Oliveira on 28/10/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension RepositoryInteractor: RepositoryViewControllerOutput, RepositoryRouterDataSource, RepositoryRouterDataDestination {
}

extension RepositoryPresenter: RepositoryInteractorOutput {
}

class RepositoryConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = RepositoryConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: RepositoryViewController) {
        
        let presenter = RepositoryPresenter()
        presenter.output = viewController
        
        let interactor = RepositoryInteractor()
        interactor.output = presenter
        
        let router = RepositoryRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
