//
//  RepositoryModels.swift
//  Gitz
//
//  Created by Anderson Oliveira on 28/10/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

struct RepositoryScene {

    struct SearchRepository {

        struct Request {
            let searchTerm: String
            let page: Int
        }
        
        struct Response {
            let result: InteractorResult<SearchResultRepository>
        }
        
        struct ViewModel {
            enum State {
                case success(searchResults: SearchResultRepository)
                case failure(errorMessage: String)
            }

            let state: State
        }
    }

    struct SelectRepository {

        struct Request {
            let selectedRepository: Repository
        }
        
        struct Response {
            let repository: Repository!
        }
    }
}
