//
//  RepositoryInteractor.swift
//  Gitz
//
//  Created by Anderson Oliveira on 28/10/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol RepositoryInteractorInput {
    func searchRepository(request: RepositoryScene.SearchRepository.Request)
    func selectRepository(request: RepositoryScene.SelectRepository.Request)
}

protocol RepositoryInteractorOutput {
    func presentSearchResult(response: RepositoryScene.SearchRepository.Response)
}

protocol RepositoryDataSource {
    var selectedRepository: Repository! { get }
}

protocol RepositoryDataDestination {
    
}

class RepositoryInteractor: RepositoryInteractorInput, RepositoryDataSource, RepositoryDataDestination {
    
    var output: RepositoryInteractorOutput?
    let searchAssetWorker: RepositoryWorker
    var selectedRepository: Repository!

    init(searchAssetWorker: RepositoryWorker = RepositoryWorker.singleton) {
        self.searchAssetWorker = searchAssetWorker
    }
    
    // MARK: Business logic

    func searchRepository(request: RepositoryScene.SearchRepository.Request) {
        searchAssetWorker.search(input: request.searchTerm) { (result) in
            
            let response = RepositoryScene.SearchRepository.Response(result: result)
            self.output?.presentSearchResult(response: response)
        }
    }

    // MARK: Select

    func selectRepository(request: RepositoryScene.SelectRepository.Request) {
        selectedRepository = request.selectedRepository
    }
}
