//
//  RepositoryDetailModels.swift
//  Gitz
//
//  Created by Anderson Oliveira on 29/10/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

struct RepositoryDetailScene {

    struct SelectedRepository {
        
        struct Request { }
        
        struct Response {
            let repository: Repository
        }
        
        struct ViewModel {
            let imageUrl: String
            let usermane: String
            let type: String
            let since: String
            let repositoryName: String
            let watchers: String
            let stargazers: String
            let forks: String
            let description: String
        }
    }
}
