//
//  RepositoryDetailConfigurator.swift
//  Gitz
//
//  Created by Anderson Oliveira on 29/10/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension RepositoryDetailInteractor: RepositoryDetailViewControllerOutput, RepositoryDetailRouterDataSource, RepositoryDetailRouterDataDestination {
}

extension RepositoryDetailPresenter: RepositoryDetailInteractorOutput {
}

class RepositoryDetailConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = RepositoryDetailConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: RepositoryDetailViewController) {
        
        let presenter = RepositoryDetailPresenter()
        presenter.output = viewController
        
        let interactor = RepositoryDetailInteractor()
        interactor.output = presenter
        
        let router = RepositoryDetailRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
